import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import localFont from "next/font/local"; //1
import "./globals.css";
import { Main } from "next/document";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const vazirFont = localFont({
  src: "../public/font/Vazirmatn-Regular.woff2",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`bg-slate-900 text-slate-200 ${vazirFont.className}`}>
        <main className="p-5">
         {children} 
        </main>
      </body>
    </html>
  );
}
